export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'
export const ADD_AUTH = 'ADD_AUTH'
export const CLEAR_AUTH = 'CLEAR_AUTH'
export const FETCH_USERS = 'FETCH_USERS'
export const CHANGE_USER_ROLES = 'CHANGE_USER_ROLES'

export const FETCH_COMPANIES = 'FETCH_COMPANIES'
export const FETCH_ACTIVE_COMPANY = 'FETCH_ACTIVE_COMPANY'
export const ADD_COMPANY = 'ADD_COMPANY'
export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const IS_COMPANY_ACTION = 'IS_COMPANY_ACTION'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_ACTIVE_PRODUCT = 'FETCH_ACTIVE_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const IS_PRODUCT_ACTION = 'IS_PRODUCT_ACTION'

export const CHANGE_LOADING = 'CHANGE_LOADING'

export const FETCH_ORDERS = "FETCH_ORDERS"
export const ADD_ORDER = "ADD_ORDER"
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID"
export const CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS"
export const IS_ORDER_ACTION = "IS_ORDER_ACTION"
